##  Pandas Challenges (Based on Your Notebook)

#### Challenge 1 – Complete Data Cleaning
#### Your manager gives you a messy dataset.
#### Perform all of the following:
#### • Load the dataset.
#### • Display dataset information.
#### • Find missing values.
#### • Remove duplicate rows.
#### • Fill missing values:
#### o Age → median
#### o Balance → mean
#### #### • Rename:
#### o Target → CustomerStatus
#### o AnnualIncome → Income
#### • Display the first 15 rows.
#### Methods expected:
#### read_csv()
#### info()
#### isnull()
#### drop_duplicates()
#### median()
#### mean()
#### fillna()
#### rename()
#### head()

In [2]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [4]:
df.isnull().sum()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [5]:
df.drop_duplicates(inplace = True)

df.duplicated().sum()

np.int64(0)

In [6]:
age_median =  df['Age'].median()
age_median

44.0

In [7]:
df["Age"] = df["Age"].fillna(age_median)
df["Age"]

0      58.0
1      65.0
2      56.0
3      55.0
4      66.0
       ...
995    34.0
996    47.0
997    31.0
998    21.0
999    63.0
Name: Age, Length: 1000, dtype: float64

In [8]:
balance_mean = df["Balance"].mean()
balance_mean

np.float64(97557.56577894738)

In [9]:
df["Balance"] = df["Balance"].fillna(balance_mean)
df["Balance"]

0       97557.565779
1        6356.540000
2      143203.920000
3      139627.880000
4       75985.460000
           ...
995    181465.650000
996     26640.990000
997    147220.820000
998     94186.480000
999    100908.400000
Name: Balance, Length: 1000, dtype: float64

In [11]:
df.rename(columns = {"Target":"CustomerStatus","AnnualIncome":"Income"},inplace = True)

In [12]:
df.head(15)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

#### Challenge 2 – Banking Report
#### The bank wants a numeric report.
#### Tasks
#### • Select only numeric columns.
#### • Display summary statistics.
#### • Convert Age and CreditScore to float.
#### • Display information again.

In [13]:
df.describe()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,950.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112458.303158,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,52409.868404,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,65922.500000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,157973.000000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [18]:
df["Age"] = df["Age"].astype(float)

df["Age"]

0      58.0
1      65.0
2      56.0
3      55.0
4      66.0
       ...
995    34.0
996    47.0
997    31.0
998    21.0
999    63.0
Name: Age, Length: 1000, dtype: float64

In [17]:
df["CreditScore"] = df["CreditScore"].astype(float)

df["CreditScore"]

0      581.0
1      732.0
2      503.0
3      463.0
4      394.0
       ...
995    761.0
996    780.0
997    733.0
998    540.0
999    559.0
Name: CreditScore, Length: 1000, dtype: float64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

#### Challenge 3 – Duplicate Investigation
#### Find duplicate customers.
#### Then
#### • Count duplicate rows.
#### • Remove duplicates.
#### • Print information before and after removing duplicates.
#### • Show the last 20 rows.

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

In [21]:
df.drop_duplicates(inplace = True)
df

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581.0,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,NaN,Stay

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   float64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 93.8+ KB

In [30]:
df.tail(20)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
980,10981,41.0,199633.0,8498,847.0,173390.590000,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541.0,59484.580000,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334.0,97557.565779,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732.0,175352.250000,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730.0,120423.190000,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488.0,126031.270000,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621.0,115161.870000,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720.0,158528.460000,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635.0,159905.730000,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884.0,44897.430000,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773.0,39653.240000,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452.0,17812.250000,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764.0,165451.490000,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594.0,149288.610000,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493.0,83666.200000,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761.0,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780.0,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733.0,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540.0,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559.0,100908.400000,6,UK,Female,NaN,Stay

####  Challenge 4 – HR Department
#### HR wants better column names.
#### Rename
#### CustomerID → Employee_ID
#### Age → EmployeeAge
#### Gender → EmployeeGender
#### AnnualIncome → Salary
#### Target → PromotionStatus
#### Then
#### • Add prefix
#### HR_
#### to every column.
#### Display 10 random records.

In [35]:
df.rename(columns = {"CustomerID":"Employee_ID","Age":"EmployeeAge","Gender":"EmployeeGender","AnnualIncome":"Salary","Target":"PromotionStatus"},inplace = True)

df.head(15)

,Employee_ID,EmployeeAge,Income,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581.0,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732.0,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503.0,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463.0,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394.0,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770.0,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891.0,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538.0,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663.0,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475.0,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870.0,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574.0,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769.0,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898.0,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393.0,151156.430000,1,USA,Other,Retail,Churn

In [37]:
df = df.add_prefix("HR_")

In [39]:
df.sample(10)

,HR_HR_Employee_ID,HR_HR_EmployeeAge,HR_HR_Income,HR_HR_Spending,HR_HR_CreditScore,HR_HR_Balance,HR_HR_Tenure,HR_HR_Geography,HR_HR_EmployeeGender,HR_HR_Segment,HR_HR_CustomerStatus
421,10422,58.0,22515.0,22455,301.0,151785.830000,6,France,Other,Corporate,Churn
622,10623,68.0,177159.0,33959,828.0,139689.950000,9,USA,Other,Retail,Stay
498,10499,34.0,166546.0,12497,643.0,130886.930000,3,UK,Male,SME,Stay
446,10447,44.0,177722.0,14839,320.0,105289.700000,0,UK,Other,Retail,Churn
650,10651,44.0,180868.0,19277,774.0,126342.440000,2,USA,Other,Corporate,Stay
695,10696,33.0,169429.0,41481,483.0,97557.565779,8,Canada,Other,Retail,Churn
268,10269,51.0,118782.0,21062,477.0,91932.710000,8,UK,Other,Corporate,Churn
820,10821,70.0,60409.0,33002,722.0,154073.560000,3,France,Female,SME,Stay
698,10699,46.0,112359.0,21153,863.0,198292.600000,5,UK,Female,SME,Stay
871,10872,53.0,80215.0,6167,721.0,171394.750000,7,NaN,Other,Corporate,Stay

#### Challenge 5 – Finance Cleaning
#### Finance department reports missing values.
#### Tasks
#### Fill
#### AnnualIncome → Median
#### Balance → Mean
#### Age → Median
#### Then
#### Generate descriptive statistics.

In [52]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [56]:
annuallncome_median =  df['AnnualIncome'].median()
annuallncome_median

112358.0

In [54]:
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [55]:
age_median = df['Age'].median()
age_median

44.0

In [57]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

#### Challenge 6 – Data Type Audit
#### The company says
#### Age and AnnualIncome are stored incorrectly.
#### Tasks
#### Convert
#### Age → int
#### AnnualIncome → float
#### Balance → float
#### Target → string
#### Print information.

In [61]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [65]:
df.fillna({'Age' : df['Age'].mean()},inplace = True)

df["Age"] = df["Age"].astype(int)

In [ ]:
df["AnnualIncome"] = df["AnnualIncome"].astype(float)

In [ ]:
df["Balance"] = df["Balance"].astype(float)

In [ ]:
df["Target "] = df["Target "].astype(str)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

#### Challenge 7 – Customer Analytics
#### Create a new DataFrame that
#### • removes Segment
#### • removes Geography
#### • removes duplicate rows
#### Display
#### • first 10 rows
#### • dataset information
#### • statistical summary

In [67]:
new_df = df.drop(["Segment", "Geography"], axis=1)

new_df = new_df.drop_duplicates()

In [68]:
new_df.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Gender,Target
0,10001,58,49184.0,2139,581,NaN,2,Male,Stay
1,10002,65,162964.0,6197,732,6356.54,1,Male,Churn
2,10003,56,26956.0,37281,503,143203.92,8,Male,Stay
3,10004,55,92926.0,925,463,139627.88,5,Male,Churn
4,10005,66,108236.0,7198,394,75985.46,5,Other,Churn
5,10006,69,31390.0,48323,770,107245.62,6,Other,Stay
6,10007,58,182141.0,24200,891,38457.72,1,Other,Churn
7,10008,67,95861.0,5729,538,173296.73,6,Female,Stay
8,10009,41,62638.0,24760,663,41901.41,4,Other,Stay
9,10010,22,179680.0,42113,475,106827.98,3,Female,Churn

In [69]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   int64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Gender        950 non-null    object
 8   Target        1000 non-null   object
dtypes: float64(2), int64(5), object(2)
memory usage: 78.1+ KB

In [70]:
new_df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,950.000000,1000.000000,1000.000000,950.000000,1000.000000
mean,10500.500000,44.202000,112458.303158,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,52409.868404,14211.735656,176.605486,55845.536430,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,65922.500000,13213.000000,441.000000,50003.880000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,95174.625000,5.000000
75%,10750.250000,57.000000,157973.000000,37960.250000,758.250000,144198.130000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

#### Challenge 8 – ML Dataset Preparation
#### Prepare a machine learning dataset.
#### Perform
#### • Remove duplicates
#### • Remove CustomerID
#### • Remove Segment
#### • Fill missing values
#### • Rename Target to Output
#### Finally
#### Display
#### head()
#### info()
#### describe()
#### value_counts(Output)

In [4]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [6]:
df.drop_duplicates(inplace =True)

In [7]:
df = df.drop(["CustomerID", "Segment"], axis=1)

In [8]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [9]:
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())

In [10]:
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

In [11]:
df = df.rename(columns={"Target": "Output"})

In [12]:
df.head()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output
0,58.0,49184.0,2139,581,97557.565779,2,France,Male,Stay
1,65.0,162964.0,6197,732,6356.540000,1,USA,Male,Churn
2,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Stay
3,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Churn
4,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Churn

In [13]:
df.describe()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000
std,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [14]:
df.value_counts()

Age   AnnualIncome  Spending  CreditScore  Balance    Tenure  Geography  Gender  Output
18.0  21864.0       38378     835          23565.72   0       Canada     Other   Churn     1
50.0  123395.0      13243     802          63551.56   9       Germany    Male    Stay      1
52.0  88876.0       49456     898          85686.77   9       Canada     Female  Stay      1
      102766.0      32391     607          50194.81   9       India      Female  Stay      1
      106960.0      25655     443          158099.62  1       Germany    Other   Churn     1
                                                                                          ..
37.0  28449.0       29973     569          69715.40   1       Canada     Male    Churn     1
      29796.0       48393     890          76309.22   0       UK         Female  Churn     1
      55947.0       25582     436          128315.23  10      USA        Male    Churn     1
      63163.0       11114     630          186947.57  3       UK         Other   Stay      1
70.0  195168.0      3679      306          82478.44   10      USA        Male    Churn     1
Name: count, Length: 901, dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           1000 non-null   float64
 1   AnnualIncome  1000 non-null   float64
 2   Spending      1000 non-null   int64
 3   CreditScore   1000 non-null   int64
 4   Balance       1000 non-null   float64
 5   Tenure        1000 non-null   int64
 6   Geography     950 non-null    object
 7   Gender        950 non-null    object
 8   Output        1000 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 78.1+ KB

#### Challenge 9 – Column Transformation
#### Create these new columns
#### NetWorth = Balance + AnnualIncome
#### AgeAfterRetirement = Age + 20
#### DoubleCreditScore = CreditScore * 2
#### IncomePerMonth = AnnualIncome / 12
#### Then
#### Display first 15 rows.

In [ ]:
df["NetWorth"] = df["Balance"] + df["AnnualIncome"]

In [ ]:
df["AgeAfterRetirement"] = df["Age"] + 20

In [ ]:
df["DoubleCreditScore"] = df["CreditScore"] * 2

In [ ]:
df["IncomePerMonth"] = df["AnnualIncome"] / 12

In [16]:
df.head(15)

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output
0,58.0,49184.0,2139,581,97557.565779,2,France,Male,Stay
1,65.0,162964.0,6197,732,6356.540000,1,USA,Male,Churn
2,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Stay
3,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Churn
4,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Churn
5,69.0,31390.0,48323,770,107245.620000,6,India,Other,Stay
6,58.0,182141.0,24200,891,38457.720000,1,India,Other,Churn
7,67.0,95861.0,5729,538,173296.730000,6,UK,Female,Stay
8,41.0,62638.0,24760,663,41901.410000,4,France,Other,Stay
9,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Churn
10,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Stay
11,69.0,102694.0,26790,574,13237.720000,9,France,Female,Churn
12,59.0,150870.0,26428,769,28574.320000,2,USA,Other,Stay
13,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Stay
14,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Churn

#### Challenge 10 – Company Report
#### Display
#### • first five rows
#### • last five rows
#### • ten random rows
#### • dataset information
#### • descriptive statistics
#### Finally rename
#### Target → Customer_Status

In [15]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [16]:
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [17]:
df.tail()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [18]:
df.sample()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
178,10179,21.0,22015.0,13897,608,NaN,2,UK,Female,Corporate,Stay

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [20]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [21]:
df.rename(columns = {"Target":" Customer_Status"},inplace=True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

#### Challenge 11 – Missing Value Report
#### Create a report showing
#### • Total missing values
#### • Numerical columns
#### • Mean of Balance
#### • Median of Age
#### • Fill missing values
#### • Display information again

In [22]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [26]:
df.isnull().sum()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [27]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [30]:
mean_balance = df["Balance"].mean()

mean_balance

np.float64(97523.53566563467)

In [31]:
median_age = df["Age"].median()
median_age

44.0

In [ ]:
df["Balance"].fillna(mean_balance, inplace=True)
df["Age"].fillna(median_age,inplace=True)

In [ ]:
for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

#### Challenge 12 – Customer Classification
#### Count
#### Stay

#### Churn
#### Then
#### Rename
#### Target → Customer_Class
#### Convert it into string.

In [3]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df["Target"].value_counts()

df = df.rename(columns={"Target": "Customer_Class"})

df["Customer_Class"] = df["Customer_Class"].astype(str)

df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

#### Challenge 13 – Sales Department
#### Rename
#### Balance → AccountBalance
#### AnnualIncome → Salary
#### CreditScore → Score
#### Add prefix
#### Sales_
#### Then
#### Display
#### sample(20)

In [4]:
df = df.rename(columns={
    "Balance": "AccountBalance",
    "AnnualIncome": "Salary",
    "CreditScore": "Score"
})

df = df.add_prefix("Sales_")

print(df.sample(20))

     Sales_CustomerID  Sales_Age  Sales_Salary  Sales_Spending  Sales_Score  \
590             10591       47.0           NaN           33950          392
722             10723       59.0       22184.0            4864          697
194             10195       57.0       61614.0           24348          681
311             10312       61.0      178589.0           40013          340
718             10719       39.0       49170.0           20496          760
443             10444       66.0       77517.0           38228          697
747             10748       29.0      138929.0           39186          506
575             10576       19.0      144253.0           10744          846
872             10873        NaN       93182.0            1450          738
752             10753       25.0       54490.0           13794          303
877             10878       47.0      169521.0           49474          897
69              10070       33.0       91984.0           29327          379
808             10809       70.0      137976.0           25712          663
192             10193       30.0      104286.0           40149          787
638             10639       20.0      151720.0           23259          703
530             10531       64.0       85162.0           32083          654
214             10215       58.0      155102.0           38186          547
245             10246       57.0      178633.0           22626          877
798             10799       31.0       56416.0           38561          300
892             10893       60.0      158979.0           36444          755

     Sales_AccountBalance  Sales_Tenure Sales_Geography Sales_Gender  \
590              79357.03             8           India          NaN
722             132074.57            10          France       Female
194             183587.36             6          Canada       Female
311             174724.09             3         Germany        Other
718              94238.06             5             USA        Other
443              70960.93             2             USA         Male
747             176509.69             1              UK       Female
575              43973.15             6         Germany       Female
872             147235.77             3             USA       Female
752             124512.07             4           India          NaN
877               4882.69             7          Canada         Male
69              142708.97             3              UK       Female
808              45148.18             6         Germany         Male
192             100273.46             0          Canada         Male
638             172080.03             2          Canada         Male
530             132742.13            10          Canada         Male
214             143708.87             4          Canada         Male
245               8238.86             0           India         Male
798             151415.54            10             USA          NaN
892              91601.42             9             USA       Female

    Sales_Segment Sales_Customer_Class
590        Retail                Churn
722        Retail                 Stay
194           NaN                 Stay
311           SME                Churn
718           SME                 Stay
443           SME                 Stay
747           SME                Churn
575           SME                 Stay
872     Corporate                 Stay
752     Corporate                Churn
877           SME                Churn
69      Corporate                Churn
808           NaN                 Stay
192     Corporate                Churn
638           SME                 Stay
530           SME                 Stay
214           SME                 Stay
245           SME                Churn
798           SME                Churn
892        Retail                 Stay

#### Challenge 14 – Interview Challenge
#### Without creating another DataFrame,
#### perform
#### • remove duplicates
#### • rename Target
#### • fill missing values
####  • convert Balance to float
#### • display summary

In [5]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

df.drop_duplicates(inplace=True)

df.rename(columns={"Target": "Customer_Class"}, inplace=True)

df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df["Balance"] = df["Balance"].astype(float)

df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,950.000000,950.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.212632,112458.303158,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.524244,52409.868404,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,30.000000,65922.500000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,58.000000,157973.000000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

#### Challenge 15 – Data Engineer Task
#### Load the dataset.
#### Create another DataFrame containing only numeric columns.
#### Drop
#### CustomerID
#### Target
#### Display summary.

In [6]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\Task_dataset - Task_dataset.csv")

numeric_df = df.select_dtypes(include="number")

numeric_df = numeric_df.drop(columns=["CustomerID", "Target"], errors="ignore")

numeric_df.describe()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000