## Exam Task on Pandas Method (Data Cleaning)

## Part 1 — Inspect & Understand the Dataset
#### Q1. Load the dataset
#### Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
#### Then display the first 10 rows.
#### Use: pd.read_csv(), head()

In [1]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\customer_analytics.csv")

df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68.0,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47.0,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65.0,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42.0,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

#### Q2. Inspect the end of the dataset
#### Display the last 15 rows.
#### Use: tail()

In [2]:
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51.0,214004.0,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573.0,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54.0,123511.0,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31.0,125500.0,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619.0,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41.0,201611.0,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61.0,128850.0,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33.0,88037.0,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43.0,122756.0,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18.0,189232.0,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

#### Q3. Random inspection
#### Display 10 random records.
#### Use: sample()

In [3]:
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
347,101928,70.0,163440.0,NaN,445,0,Pune,Corporate,Branch,2021-05-11 00:00:00,Yes,High,4326.03,4,5.6
1055,100315,48.0,155406.0,268718.02,597,11,Bangalore,Corporate,Online,2022-03-15 00:00:00,Yes,Medium,NaN,85,6.8
653,100278,22.0,60488.0,6608.08,850,2,Bangalore,SME,Online,2022-10-01 00:00:00,No,High,30996.88,48,7.2
10,101525,47.0,178741.0,22931.96,341,1,Hyderabad,Retail,Mobile,2023-03-02 00:00:00,Yes,High,NaN,78,5.6
749,100670,46.0,81088.0,NaN,743,10,Bangalore,Corporate,Agent,2023-11-14 00:00:00,Yes,Low,43609.08,119,6.8
931,100616,33.0,114152.0,-,396,15,Chennai,Corporate,Branch,2024-12-07 00:00:00,Yes,High,17335.39,77,2.5
1783,101521,68.0,75601.0,41365.58,840,14,Kolkata,SME,Agent,2024-12-15 00:00:00,Yes,Low,40803.44,76,1.1
60,101564,45.0,70232.0,204405.9,542,14,pune,Corporate,Branch,2022-11-04 00:00:00,Yes,High,29657.43,57,9.4
836,100683,52.0,82716.0,37314.85,723,5,Hyderabad,Premium,Agent,NaN,No,Low,17254.79,54,9.5

#### Q4. Dataset audit
#### Use info() to identify:
#### • Number of rows
#### • Number of columns
#### • Columns with missing values
#### • Columns having incorrect/object datatypes
#### Use: info()

In [4]:
df.shape

(2040, 15)

In [5]:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [6]:
df.dtypes

Customer_ID             int64
Age                    object
Annual_Income          object
Account_Balance        object
Credit_Score           object
Tenure_Years            int64
City                   object
Segment                object
Channel                object
Join_Date              object
Active                 object
Risk_Level             object
Monthly_Spend          object
Transactions           object
Satisfaction_Score    float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

#### Q5. Missing-value audit
#### Calculate the number of missing values in every column.
#### Then verify the result using both:
#### isnull()
#### and
#### isna()

In [8]:
df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [9]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

## Part 2 — Detect & Fix Data Quality Problems
#### Q6. Duplicate investigation
#### Find how many duplicate rows exist.
#### Do not remove them yet.
#### Use: duplicated()

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2040, dtype: bool

#### Q7. Remove duplicates
#### Remove all duplicate records and store the cleaned result back into df.
#### Then verify that duplicates no longer exist.
####  Use: drop_duplicates(), duplicated()

In [11]:
df = df.drop_duplicates()
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [12]:
df.duplicated().sum()

np.int64(0)

#### Q8. Numeric column investigation
#### Select only numeric columns.
#### Identify which columns are currently numeric and which potentially numeric columns have
#### become object because of invalid values.
#### Use: select_dtypes()

In [13]:
df.select_dtypes(include="number")

      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2000 rows x 3 columns]

In [14]:
num_colm = df.select_dtypes(include = "number").columns

num_colm

Index(['Customer_ID', 'Tenure_Years', 'Satisfaction_Score'], dtype='object')

In [15]:
obj_colm = df.select_dtypes(include = "object").columns

obj_colm

Index(['Age', 'Annual_Income', 'Account_Balance', 'Credit_Score', 'City',
       'Segment', 'Channel', 'Join_Date', 'Active', 'Risk_Level',
       'Monthly_Spend', 'Transactions'],
      dtype='object')

In [16]:
for col in obj_colm:
    converted = pd.to_numeric(df[col],errors = "coerce")

    num_count = converted.notna().sum()

    if num_count > 0:
        print(f"{col}-->potential numeric ({num_count}numeric values)")

Age-->potential numeric (1873numeric values)
Annual_Income-->potential numeric (1851numeric values)
Account_Balance-->potential numeric (1832numeric values)
Credit_Score-->potential numeric (1960numeric values)
Active-->potential numeric (28numeric values)
Monthly_Spend-->potential numeric (1854numeric values)
Transactions-->potential numeric (1960numeric values)

#### Q9. Fix Age
#### The Age column contains:
#### • Valid numbers
#### • Missing values
#### • Invalid text such as unknown, N/A, etc.
#### Convert Age into a proper numeric column.
#### Invalid values should become missing values.
#### Then fill missing Age values using the median age.
#### pd.to_numeric(), median(), fillna()

In [17]:
df['Age'] = pd.to_numeric(df['Age'],errors = 'coerce')

median_age = df['Age'].median()

df['Age'] = df['Age'].fillna(median_age)

df['Age']

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64

#### Q10. Fix Annual Income
#### Clean Annual_Income.
#### Requirements:
#### 1. Convert invalid values to missing.
#### 2. Convert the column to a numeric datatype.
#### 3. Calculate the median.
#### 4. Fill missing values using the median.
### Use: pd.to_numeric(), median(), fillna(), astype()

In [18]:
df['Annual_Income'] = pd.to_numeric(df['Annual_Income'],errors = 'coerce')

df["Annual_income"] = df ["Annual_Income"].astype("float")

median_income = df['Annual_Income'].median()

df['Annual_Income'] = df['Annual_Income'].fillna(median_income)

print(df[["Annual_Income"]].head())
print(df["Annual_Income"].dtype)
print(df["Annual_Income"].isna().sum())

   Annual_Income
0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
float64
0

## Part 3 — Numerical Cleaning
#### Q11. Clean Account Balance
#### The Account_Balance column contains invalid strings and missing values.
#### Clean the column and replace missing values with the mean Account Balance.
#### Use:
#### • pd.to_numeric()
#### • mean()
#### • fillna()

In [19]:
df["Account_Balance"] = pd.to_numeric(df["Account_Balance"],errors = "coerce")

df["Account_Balance"] = df["Account_Balance"].astype(float)

mean_balance = df["Account_Balance"].mean()

df["Account_Balance"] = df["Account_Balance"].fillna(mean_balance)

print(df["Account_Balance"].head)
print(df["Account_Balance"].dtype)
print(df[["Account_Balance"]].isna().sum())

<bound method NDFrame.head of 0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2000, dtype: float64>
float64
Account_Balance    0
dtype: int64

#### Q12. Clean Credit Score
#### Clean Credit_Score.
#### Invalid values should become missing.
#### Then replace missing values with the median Credit Score.
#### Finally convert the column to integer.
#### Use:
#### • pd.to_numeric()
#### • median()
#### • fillna()
#### • astype()

In [20]:
df["Credit_Score"] = pd.to_numeric(df["Credit_Score"],errors="coerce")

median_score = df["Credit_Score"].median()

df["Credit_Score"] = df["Credit_Score"].fillna(median_score)

df["Credit_Score"] = df["Credit_Score"].astype(int)

print(df["Credit_Score"].head)
print(df["Credit_Score"].dtype)
print(df["Credit_Score"].isna().sum())

<bound method NDFrame.head of 0       772
1       374
2       668
3       315
4       370
       ...
2035    677
2036    392
2037    737
2038    794
2039    783
Name: Credit_Score, Length: 2000, dtype: int64>
int64
0

#### Q13. Clean Monthly Spend
#### Clean Monthly_Spend.
#### Then:
#### • Convert it to numeric.
#### • Replace invalid values.
#### • Replace missing values using the median.
#### • Make sure the final column is numeric.

In [21]:
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors = "coerce")

median_spend = df["Monthly_Spend"].median()

df["Monthly_Spend"] = df["Monthly_Spend"].fillna(median_spend)

df["Monthly_Spend"]= df["Monthly_Spend"].astype(float)

print(df["Monthly_Spend"].head())
print(df["Monthly_Spend"].dtype)
print(df["Monthly_Spend"].isna().sum())

0    23066.19
1    24625.17
2    28536.34
3    12869.71
4    34163.02
Name: Monthly_Spend, dtype: float64
float64
0

#### Q14. Clean Transactions
#### The Transactions column contains invalid strings.
#### Convert it to numeric and replace invalid values with the median number of transactions.
#### Then convert the final column to integer.

In [22]:
df["Transactions"] = pd.to_numeric(df["Transactions"],errors="coerce")

median_trans = df["Transactions"].median()

df["Transactions"] = df["Transactions"].fillna(median_trans)

df["Transactions"] = df["Transactions"].astype(int)

print(df["Transactions"].head())

print(df["Transactions"].dtype)

print(df[["Transactions"]].isna().sum())

0    135
1    106
2    146
3    115
4     94
Name: Transactions, dtype: int64
int64
Transactions    0
dtype: int64

#### Q15. Clean Satisfaction Score
#### Clean Satisfaction_Score.
#### Replace missing/invalid values using the mean Satisfaction Score.
#### Then convert the column to float.

In [23]:
df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"],errors="coerce")

mean_score = df["Satisfaction_Score"].mean()

df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(mean_score)

df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)

print(df[["Satisfaction_Score"]].head(10))

print(df["Satisfaction_Score"].dtype)

print(df["Satisfaction_Score"].isna().sum())

   Satisfaction_Score
0                 3.1
1                 8.2
2                 6.3
3                 9.7
4                 3.7
5                 8.5
6                 2.8
7                 9.7
8                 7.1
9                 9.1
float64
0

## Part 4 — Date Cleaning
#### Q16. Investigate Join_Date
#### Inspect the Join_Date column.
#### Identify the problems caused by:
#### • Missing dates
#### • Different date formats
#### • Invalid date strings
#### Do not clean it yet.

In [57]:
print(df["Join_Date"].head(10))

print(df["Join_Date"].isna().sum())

print(df["Join_Date"].unique()[:20])

check_dates = pd.to_datetime(df["Join_Date"], errors="coerce")

print(check_dates.isna().sum())

print(df.loc[check_dates.isna(), ["Join_Date"]])

0    2022-08-15 00:00:00
1    2025-01-11 00:00:00
2    2024-08-01 00:00:00
3    2021-05-15 00:00:00
4    2026-02-03 00:00:00
5    2023-06-04 00:00:00
6    2024-01-16 00:00:00
7    2024-06-26 00:00:00
8    2025-03-12 00:00:00
9    2021-10-07 00:00:00
Name: Join_Date, dtype: object
102
['2022-08-15 00:00:00' '2025-01-11 00:00:00' '2024-08-01 00:00:00'
 '2021-05-15 00:00:00' '2026-02-03 00:00:00' '2023-06-04 00:00:00'
 '2024-01-16 00:00:00' '2024-06-26 00:00:00' '2025-03-12 00:00:00'
 '2021-10-07 00:00:00' '2023-03-02 00:00:00' '2025-11-22 00:00:00'
 '2021-06-25 00:00:00' '2025-11-19 00:00:00' '2025-08-26 00:00:00'
 '2024-05-05 00:00:00' '2022-01-07 00:00:00' '2022-05-25 00:00:00'
 '2022-10-07 00:00:00' '2023-08-10 00:00:00']
128
     Join_Date
20         NaN
64         NaN
84         NaN
97         NaN
100        NaN
...        ...
1966       NaN
2001       NaN
2002       NaN
2016       NaN
2039       NaN

[128 rows x 1 columns]

#### Q17. Convert Join_Date
#### Convert Join_Date into a proper Pandas datetime column.
#### Any invalid dates should become missing values.
#### Use: pd.to_datetime()

In [25]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"],format="mixed",errors="coerce")

print(df["Join_Date"].head())

print(df["Join_Date"].dtype)

print(df["Join_Date"].isna().sum())

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
Name: Join_Date, dtype: datetime64[ns]
datetime64[ns]
125

#### Q18. Handle missing dates
#### After conversion, find how many missing dates remain.
#### Then replace missing dates appropriately using a reasonable date-based strategy.

In [26]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"],format="mixed",errors="coerce")

missing_dates = df["Join_Date"].isna().sum()

median_date = df["Join_Date"].median()

df["Join_Date"] = df["Join_Date"].fillna(median_date)

print(df["Join_Date"].head(10))
print(df["Join_Date"].dtype)
print(df["Join_Date"].isna().sum())

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
5   2023-06-04
6   2024-01-16
7   2024-06-26
8   2025-03-12
9   2021-10-07
Name: Join_Date, dtype: datetime64[ns]
datetime64[ns]
0

## Part 5 — Categorical Cleaning
#### Q19. Clean City
#### The City column contains values such as:
##### Mumbai
#### mumbai
#### Mumbai
#### mumbai
#### Standardize the values so that logically identical cities are represented consistently.
#### Then check the unique frequency distribution.
#### Use: replace(), value_counts()

In [27]:
df["City"] = df["City"].str.strip()

df["City"] = df["City"].str.title()

print(df["City"].value_counts())

City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64

#### Q20. Analyze Segment
#### Check the frequency of:
#### Retail
#### SME
#### Corporate
#### Premium
#### Also determine whether missing values exist.
#### Then replace missing Segment values with the most appropriate category based on your
#### analysis.
#### Use: value_counts(), fillna()

In [28]:
print(df["Segment"].value_counts())

print(df["Segment"].isna().sum())

most_common_segment = df["Segment"].mode()[0]

df["Segment"] = df["Segment"].fillna(most_common_segment)

print(df["Segment"].isna().sum())

print(df["Segment"].value_counts())

Segment
Premium      516
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64
100
0
Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

#### Q21. Clean Active
#### Active is supposed to be a binary column, but it contains:
#### Yes
#### No
#### Y
#### N
#### YES
#### NO
#### yes
#### no
#### 1
#### 0
#### Transform these into a consistent representation:
#### Yes
#### No
#### Then verify the result with value_counts().
#### Use: replace(), value_counts()

In [29]:
df["Active"] = df["Active"].astype(str).str.strip().str.upper()

df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "1": "Yes",

    "N": "No",
    "NO": "No",
    "0": "No"
})

print(df["Active"].value_counts(dropna=False))

Active
Yes    1345
No      597
NAN      58
Name: count, dtype: int64

#### Q22. Clean Risk_Level
#### Check the distribution of:
#### High
#### Medium
#### Low
#### Verify whether missing values exist.
#### Then display the final class distribution.

In [30]:
print(df["Risk_Level"].value_counts())

print(df["Risk_Level"].isna().sum())

df["Risk_Level"] = df["Risk_Level"].fillna(df["Risk_Level"].mode()[0])

print(df["Risk_Level"].value_counts())

print(df["Risk_Level"].isna().sum())

Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64
0
Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64
0

## Part 6 — Column Transformation
#### Q23. Rename columns
#### Rename these columns:
#### Customer_ID → Customer_ID
#### Annual_Income → AnnualIncome
#### Account_Balance → AccountBalance
#### Credit_Score → CreditScore
#### Tenure_Years → Tenure
#### Join_Date → CustomerJoinDate
#### Risk_Level → RiskLevel
#### Monthly_Spend → MonthlySpend
#### Satisfaction_Score → SatisfactionScore
#### Use rename().

In [31]:
df = df.rename(columns={
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})

print(df.columns)

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore',
       'Annual_income'],
      dtype='object')

#### Q24. Add a prefix
#### Add:
#### Customer_
#### to every column.
#### Example:
#### Age
#### becomes:
#### Customer_Age
#### Use: add_prefix()

In [32]:
df = df.add_prefix("Customer_")

print(df.columns)

Index(['Customer_Customer_ID', 'Customer_Age', 'Customer_AnnualIncome',
       'Customer_AccountBalance', 'Customer_CreditScore', 'Customer_Tenure',
       'Customer_City', 'Customer_Segment', 'Customer_Channel',
       'Customer_CustomerJoinDate', 'Customer_Active', 'Customer_RiskLevel',
       'Customer_MonthlySpend', 'Customer_Transactions',
       'Customer_SatisfactionScore', 'Customer_Annual_income'],
      dtype='object')

#### Q25. Remove unnecessary column
### Determine whether Customer_ID should be retained for analysis.
#### Create a cleaned DataFrame without the identifier column.
#### Use: drop()

In [56]:
import pandas as pd

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\customer_analytics.csv")

df_clean = df.drop("Customer_ID", axis=1)

print(df_clean.head())

print(df_clean.columns)

    Age Annual_Income Account_Balance Credit_Score  Tenure_Years         City  \
0  55.0       44033.0       111350.85          772             3    Bangalore
1  32.0      215546.0       254378.37          374             8        Delhi
2  23.0      226403.0       159975.42          668            12      Chennai
3  66.0       87824.0        295741.6          315            14       Mumbai
4  67.0       31570.0       242423.78          370             4   bangalore

   Segment Channel            Join_Date Active Risk_Level Monthly_Spend  \
0      SME   Agent  2022-08-15 00:00:00    Yes        Low      23066.19
1   Retail   Agent  2025-01-11 00:00:00    Yes       High           NaN
2  Premium   Agent  2024-08-01 00:00:00     No     Medium      28536.34
3  Premium   Agent  2021-05-15 00:00:00    Yes       High      12869.71
4   Retail   Agent  2026-02-03 00:00:00     No       High      34163.02

  Transactions  Satisfaction_Score
0          135                 3.1
1          106                 8.2
2          146                 6.3
3          115                 9.7
4           94                 3.7
Index(['Age', 'Annual_Income', 'Account_Balance', 'Credit_Score',
       'Tenure_Years', 'City', 'Segment', 'Channel', 'Join_Date', 'Active',
       'Risk_Level', 'Monthly_Spend', 'Transactions', 'Satisfaction_Score'],
      dtype='object')

## Part 7 — Create New Columns
#### Q26. Create Annual Income in Lakhs
#### Create:
#### Income_Lakhs
#### using:
#### AnnualIncome / 100000
#### Then check the first 10 records.

In [51]:
df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")
df["Annual_Income"] = df["Annual_Income"].fillna(df["Annual_Income"].median())

df["Income_Lakhs"] = df["Annual_Income"] / 100000
print(df[["Annual_Income", "Income_Lakhs"]].head(10))

   Annual_Income  Income_Lakhs
0        44033.0      0.440330
1       215546.0      2.155460
2       226403.0      2.264030
3        87824.0      0.878240
4        31570.0      0.315700
5        37087.0      0.370870
6        67229.0      0.672290
7       139999.5      1.399995
8       153267.0      1.532670
9       139999.5      1.399995

#### Q27. Create Monthly Income
#### Create:
#### MonthlyIncome
#### using:
#### AnnualIncome / 12
#### Then create:
#### Income_After_Spending
#### using:
#### MonthlyIncome - MonthlySpend

In [53]:
df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"], errors="coerce")

df["MonthlyIncome"] = df["Annual_Income"] / 12

df["Income_After_Spending"] = (df["MonthlyIncome"] - df["Monthly_Spend"])

print(df[["Annual_Income","MonthlyIncome","Monthly_Spend","Income_After_Spending"]].head(10))

   Annual_Income  MonthlyIncome  Monthly_Spend  Income_After_Spending
0        44033.0    3669.416667       23066.19          -19396.773333
1       215546.0   17962.166667            NaN                    NaN
2       226403.0   18866.916667       28536.34           -9669.423333
3        87824.0    7318.666667       12869.71           -5551.043333
4        31570.0    2630.833333       34163.02          -31532.186667
5        37087.0    3090.583333       15121.16          -12030.576667
6        67229.0    5602.416667       17655.61          -12053.193333
7       139999.5   11666.625000        1720.85            9945.775000
8       153267.0   12772.250000       38043.07          -25270.820000
9       139999.5   11666.625000       11472.36             194.265000

#### Q28. Create Balance-to-Income Ratio
#### Create:
#### Balance_Income_Ratio
#### using:
#### AccountBalance / AnnualIncome
#### Then inspect the first 10 rows.
#### Think carefully about division by zero and missing values.

In [55]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\customer_analytics.csv")

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")
df["Account_Balance"] = pd.to_numeric(df["Account_Balance"], errors="coerce")

df["Annual_Income"] = df["Annual_Income"].replace(0, np.nan)

df["Balance_Income_Ratio"] = (df["Account_Balance"] / df["Annual_Income"])

print(df[["Account_Balance","Annual_Income","Balance_Income_Ratio"]].head(10))

   Account_Balance  Annual_Income  Balance_Income_Ratio
0        111350.85        44033.0              2.528805
1        254378.37       215546.0              1.180158
2        159975.42       226403.0              0.706596
3        295741.60        87824.0              3.367435
4        242423.78        31570.0              7.678929
5        180084.44        37087.0              4.855730
6         99629.81        67229.0              1.481947
7         61030.94            NaN                   NaN
8        221707.97       153267.0              1.446547
9         41126.84            NaN                   NaN

In [58]:
df.to_csv("customer_analytics_clean.csv", index=False)

In [59]:
import os

print(os.path.exists(r"C:\Users\rohit\Downloads\customer_analytics_clean.csv"))

False