## Flight Price Datasets— 30 Clean Questions

#### 1. Load the Flight Price dataset into a Pandas DataFrame and display the first five rows.

In [1]:
import pandas as pd

df = pd.read_excel("C:\\Users\\rohit\\Downloads\\Data_Train.xlsx")

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

#### 2. Find the number of rows and columns in the dataset.

In [2]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("Shape of the dataset:", df.shape)

Number of rows: 10683
Number of columns: 11
Shape of the dataset: (10683, 11)

#### 3. Display all column names in the dataset.

In [3]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

#### 4. Display the data types of all columns.

In [4]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

#### 5. Use df.info() to inspect the structure of the dataset.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

#### 6. Check the number of missing values in each column.

In [6]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

#### 7. Check the percentage of missing values in each column.

In [7]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

#### 8. Display the unique values and frequency of each value in the Airline column.

In [8]:
print(df["Airline"].unique())

print(df["Airline"].value_counts())

['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']
Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

#### 9. Display the frequency distribution of Total_Stops, including missing values.

In [9]:
df["Total_Stops"].value_counts(dropna=False)

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64

#### 10.Convert Date_of_Journey into a datetime format.

In [10]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], format="%d/%m/%Y")

df["Date_of_Journey"].dtype

dtype('<M8[ns]')

#### 11.Extract the day from Date_of_Journey and create a day column.

In [11]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], format="%d/%m/%Y")

df["day"] = df["Date_of_Journey"].dt.day

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1

#### 12.Extract the month from Date_of_Journey and create a month column.

In [12]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], format="%d/%m/%Y")

df["month"] = df["Date_of_Journey"].dt.month

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3

#### 13.Extract the year from Date_of_Journey and create a year column.

In [13]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], format="%d/%m/%Y")

df["year"] = df["Date_of_Journey"].dt.year

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

#### 14.Drop the original Date_of_Journey column after extracting the required features.

In [14]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], format="%d/%m/%Y")

df["day"] = df["Date_of_Journey"].dt.day
df["month"] = df["Date_of_Journey"].dt.month
df["year"] = df["Date_of_Journey"].dt.year

df.drop("Date_of_Journey", axis=1, inplace=True)

df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

####  15.Convert Dep_Time into datetime format and extract the departure hour into Dep_Hour.

In [16]:
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"], format="%H:%M")

df["Dep_Hour"] = df["Dep_Time"].dt.hour

df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-08-11 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-11 05:50:00,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-08-11 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-11 18:05:00,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-11 16:50:00,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16

#### 16.Extract the departure minute from Dep_Time and create Dep_Minute.

In [17]:
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"], format="%H:%M")

df["Dep_Minute"] = df["Dep_Time"].dt.minute


df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-08-11 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-11 05:50:00,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-08-11 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-11 18:05:00,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-11 16:50:00,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50

#### 17.Drop the original Dep_Time column after extracting the required features.

In [19]:
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"], format="%H:%M")

df["Dep_Hour"] = df["Dep_Time"].dt.hour
df["Dep_Minute"] = df["Dep_Time"].dt.minute

df.drop("Dep_Time", axis=1, inplace=True)

df.head()

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50

#### 18.Extract only the time portion from Arrival_Time.

In [22]:
df["Arrival_Time"] = df["Arrival_Time"].astype(str).str.split().str[0]

print(df.head())

       Airline    Source Destination                  Route Arrival_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL     01:10:00
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR     13:15:00
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK     04:25:00
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR     23:30:00
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL     21:35:00

  Duration Total_Stops Additional_Info  Price  day  month  year  Dep_Hour  \
0   2h 50m    non-stop         No info   3897   24      3  2019        22
1   7h 25m     2 stops         No info   7662    1      5  2019         5
2      19h     2 stops         No info  13882    9      6  2019         9
3   5h 25m      1 stop         No info   6218   12      5  2019        18
4   4h 45m      1 stop         No info  13302    1      3  2019        16

   Dep_Minute
0          20
1          50
2          25
3           5
4          50

#### 19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.

In [24]:
df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"], format="mixed")

df["Arrival_Hour"] = df["Arrival_Time"].dt.hour
df["Arrival_Minute"] = df["Arrival_Time"].dt.minute

df["Arrival_Time"].head(10)

0   2026-08-11 01:10:00
1   2026-08-11 13:15:00
2   2026-08-11 04:25:00
3   2026-08-11 23:30:00
4   2026-08-11 21:35:00
5   2026-08-11 11:25:00
6   2026-08-11 10:25:00
7   2026-08-11 05:05:00
8   2026-08-11 10:25:00
9   2026-08-11 19:15:00
Name: Arrival_Time, dtype: datetime64[ns]

#### 20.Drop the original Arrival_Time column after extracting the required features.

In [25]:
df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"], format="mixed")

df["Arrival_Hour"] = df["Arrival_Time"].dt.hour
df["Arrival_Minute"] = df["Arrival_Time"].dt.minute

df.drop("Arrival_Time", axis=1, inplace=True)

df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35

#### 21.Extract the hour component from Duration and create Duration_Hour. Handle invalid or missing extracted values appropriately.

In [26]:
df["Duration_Hour"] = df["Duration"].str.extract(r"(\d+)h")

df["Duration_Hour"] = df["Duration_Hour"].fillna(0).astype(int)

df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10,2
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15,7
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25,19
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35,4

#### 22.Extract the minute component from Duration and create Duration_Minute. Handle invalid or missing extracted values appropriately.

In [27]:
df["Duration_Minute"] = df["Duration"].str.extract(r"(\d+)m")

df["Duration_Minute"] = df["Duration_Minute"].fillna(0).astype(int)

df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35,4,45

#### 23.Drop the original Duration column after creating the numerical duration features.

In [28]:
df["Duration_Hour"] = df["Duration"].str.extract(r"(\d+)h")
df["Duration_Hour"] = df["Duration_Hour"].fillna(0).astype(int)

df["Duration_Minute"] = df["Duration"].str.extract(r"(\d+)m")
df["Duration_Minute"] = df["Duration_Minute"].fillna(0).astype(int)

df.drop("Duration", axis=1, inplace=True)

df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,16,50,21,35,4,45

#### 24.Replace non-stop in Total_Stops with 0 stops.

In [29]:
df["Total_Stops"] = df["Total_Stops"].replace("non-stop", "0 stops")

df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,0 stops,No info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,16,50,21,35,4,45

#### 25.Extract only the numerical value from Total_Stops and convert the column into an integer data type. Handle missing or invalid values appropriately.

In [30]:
df["Total_Stops"] = df["Total_Stops"].replace("non-stop", "0 stops")

df["Total_Stops"] = df["Total_Stops"].str.extract(r"(\d+)")

df["Total_Stops"] = df["Total_Stops"].fillna(0).astype(int)

df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,16,50,21,35,4,45

#### 26.Split the Route column using → as the separator and create Route_1, Route_2, Route_3, Route_4, and Route_5.

In [32]:
route = df["Route"].str.split("→", expand=True)

route.columns = [f"Route_{i+1}" for i in range(route.shape[1])]

df = pd.concat([df, route], axis=1)

df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,...,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5,Route_6
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,...,1,10,2,50,BLR,DEL,None,None,None,None
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,...,13,15,7,25,CCU,IXR,BBI,BLR,None,None
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,...,4,25,19,0,DEL,LKO,BOM,COK,None,None
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,...,23,30,5,25,CCU,NAG,BLR,None,None,None
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,...,21,35,4,45,BLR,NAG,DEL,None,None,None

#### 27.Identify the missing values created in Route_3, Route_4, and Route_5 after splitting the route.

In [36]:
route = df["Route"].str.split("→", expand=True)


route.columns = [f"Route_{i+1}" for i in range(route.shape[1])]


df = pd.concat([df, route], axis=1)


df[["Route_3", "Route_4", "Route_5"]].isnull().sum()

Route_3     3492
Route_3     3492
Route_3     3492
Route_3     3492
Route_3     3492
Route_4     9117
Route_4     9117
Route_4     9117
Route_4     9117
Route_4     9117
Route_5    10637
Route_5    10637
Route_5    10637
Route_5    10637
Route_5    10637
dtype: int64

#### 28.Replace the missing values in the route columns with an appropriate value such as None.

In [37]:
route = df["Route"].str.split("→", expand=True)

route.columns = [f"Route_{i+1}" for i in range(route.shape[1])]

df = pd.concat([df, route], axis=1)


df[["Route_3", "Route_4", "Route_5"]] = df[
    ["Route_3", "Route_4", "Route_5"]
].fillna("None")


df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,...,Route_3,Route_4,Route_5,Route_6,Route_1,Route_2,Route_3,Route_4,Route_5,Route_6
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,...,None,None,None,None,BLR,DEL,None,None,None,None
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,...,BBI,BBI,BBI,None,CCU,IXR,BBI,BBI,BBI,None
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,...,BOM,BOM,BOM,None,DEL,LKO,BOM,BOM,BOM,None
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,...,BLR,BLR,BLR,None,CCU,NAG,BLR,BLR,BLR,None
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,...,DEL,DEL,DEL,None,BLR,NAG,DEL,DEL,DEL,None

#### 29.Drop the original Route column after creating and cleaning the route features.

In [38]:
route = df["Route"].str.split("→", expand=True)

route.columns = [f"Route_{i+1}" for i in range(route.shape[1])]

df = pd.concat([df, route], axis=1)

df = df.fillna({"Route_3": "None", "Route_4": "None", "Route_5": "None"})

df.drop("Route", axis=1, inplace=True)

df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,day,month,year,Dep_Hour,...,Route_3,Route_4,Route_5,Route_6,Route_1,Route_2,Route_3,Route_4,Route_5,Route_6
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,22,...,None,None,None,None,BLR,DEL,None,None,None,None
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,5,...,BBI,BBI,BBI,None,CCU,IXR,BBI,BLR,None,None
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,9,...,BOM,BOM,BOM,None,DEL,LKO,BOM,COK,None,None
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,18,...,BLR,BLR,BLR,None,CCU,NAG,BLR,None,None,None
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,16,...,DEL,DEL,DEL,None,BLR,NAG,DEL,None,None,None

#### 30.After completing all data cleaning and feature engineering, separate the
#### dataset into X (independent variables) and y (target variable), where Price is the target.

In [39]:
X = df.drop("Price", axis=1)
y = df["Price"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print(X.head())
print(y.head())

X shape: (10683, 56)
y shape: (10683,)
       Airline    Source Destination  Total_Stops Additional_Info  day  month  \
0       IndiGo  Banglore   New Delhi            0         No info   24      3
1    Air India   Kolkata    Banglore            2         No info    1      5
2  Jet Airways     Delhi      Cochin            2         No info    9      6
3       IndiGo   Kolkata    Banglore            1         No info   12      5
4       IndiGo  Banglore   New Delhi            1         No info    1      3

   year  Dep_Hour  Dep_Minute  ... Route_3 Route_4 Route_5 Route_6 Route_1  \
0  2019        22          20  ...    None    None    None    None    BLR
1  2019         5          50  ...    BBI     BBI     BBI     None    CCU
2  2019         9          25  ...    BOM     BOM     BOM     None    DEL
3  2019        18           5  ...     BLR     BLR     BLR    None    CCU
4  2019        16          50  ...     DEL     DEL     DEL    None    BLR

  Route_2 Route_3 Route_4 Route_5 Route_6
0     DEL    None    None    None    None
1    IXR     BBI      BLR    None    None
2    LKO     BOM      COK    None    None
3    NAG      BLR    None    None    None
4    NAG      DEL    None    None    None

[5 rows x 56 columns]
0     3897
1     7662
2    13882
3     6218
4    13302
Name: Price, dtype: int64